INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (1, 1014, 1006, 5, 'Finally! A website where I can search for new creators, but also read their reviews first to make sure they''re worth subscribing to.', '2021-08-16 17:03:49', '2021-08-16 17:03:49', 'Great place to find new creators!', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (2, 1018, 1006, 5, 'Privy provides creators of all types a safe, trustworthy space to promote their work, while allowing their consumers to leave reviews on their work.

It''s TrustPilot for makers.. A significant resource, for all involved, that has been missing in today''s grind and hustle culture.', '2021-08-16 17:47:56', '2021-08-16 17:47:56', 'Amazing!', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (3, 1018, 938, 5, 'Very active, reasonably priced, and responsive. I highly recommend subbing to Sofya''s OF.', '2021-08-16 17:50:16', '2021-08-24 03:45:26', 'Great content!', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (4, 1022, 1006, 4, 'This platform is super easy to use and extremely user-friendly. I was able to review a few of my favorite creators. It''s a great way to help them gain subs and make more money.', '2021-08-17 01:48:19', '2021-08-17 01:48:19', 'The platform we needed!', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (5, 1031, 1008, 5, '', '2021-08-18 16:41:08', '2021-08-18 16:41:08', '', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (9, 1054, 1006, 5, 'I just recently started my own OnlyFans channel and I will definitely be sending my subs here to review me! I love this concept!', '2021-08-24 03:38:00', '2021-08-24 03:38:00', 'New subscribers!', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (10, 1086, 1, 5, '', '2021-08-26 07:45:36', '2021-08-26 07:45:36', 'Awesome', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (11, 1102, 10, 5, '', '2021-08-29 06:52:33', '2021-08-29 06:52:33', '', 'published', null, 0, null, 'onlyfans');
INSERT INTO privy.reviews (id, reviewer_id, creator_id, rating, description, created_at, updated_at, title, status, response, is_verified, flag_reason, platform) VALUES (13, 1157, 33, 5, 'She is the perfect example of the "girl next door". Sweet, sexy, and great to interact with. I am new to the OF world but she is probably one of the few who genuinely will talk to you and get to know you, not just spam your inbox. If you want to chat with a hot little number, look no further.', '2021-09-26 23:53:39', '2021-09-27 02:12:50', 'Worth every dollar!', 'published', null, 0, null, 'onlyfans');